### ISSUE TITLE
Snabbare animationer

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DNollK.se#13]
Animationerna när man stänger och öppnar nyheter och byter flyttar sidopanelen är riktigt långsamma på mobiler..

Det beror troligen på att de använder javascript och inte css. Det hade vart bra att lösa detta så hemsidan går att använda på telefoner också.

**Comment by tairoman** [comment]
Det går la att lösa med en css-transition? Jag kan kolla på det.

**Comment by tairoman** [comment]
Om du inte vill det förstås ^^

**Comment by Jassob** [comment]
Näe kör på! Ta bort min assign bara ;)

**Comment by Jassob** [comment]
@tairoman, nu assignade jag dig på detta eftersom som du visade intresse!

**Comment by tairoman** [comment]
Finfint!

**Comment by Jassob** [comment]
Yo, jag har gjort om lite.

Funkar det bättre för dig också nu? 
Här är committen jag fixade: [Massa götta](https://github.com/dtekcth/DNollK.se/commit/58489590787ffe8d93ed7a71a6430b2362acbfb0)

**Comment by Jassob** [comment]
This issue was moved to Jassob/DNollK.se#20
