### ISSUE TITLE
Stödja paginering

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DNollK.se#14]
Vi borde stödja paginering för nyheterna.
Som det är nu så hämtar vi de senaste 10 och visar dem på hemsidan och det är lite olyckligt ifall man någonsin vill gå igenom arkivet (varför man nu skulle vilja det..)

Vi har i alla fall två alternativ, det ena är att stödja paginering där man helt enkelt får en knapp som säger typ 'nästa sida' eller nåt, eller så hittar vi på någon form av AJAX/'continuous loading'-historia.

**Comment by Jassob** [comment]
Jag anser att det räcker med paginering.

Det skulle man enkelt kunna implementera med hjälp av HTTP's querystring.
Exempel om vi behåller vår nuvarande inställning att bara visa 10 nyheter i taget:

* `http://dnollk.se/` - Visar de senaste 10 nyheterna från nuvarande året.
* `http://dnollk.se/?page=1` - Visar de senaste 10 nyheterna från nuvarande året (man kanske vill använda 0 för att ha lite programmeringshumor..?)
* `http://dnollk.se/?page=2` - Visar de 11-20 senaste nyheterna från nuvarande året.
* `http://dnollk.se/?count=20` - Visar de 20 senaste nyheterna från nuvarande året.
* `http://dnollk.se/?page=2?count=20` - Visar de 21-40 senaste nyheterna från nuvarande året.

För andra år än det nuvarande lägger man bara till året efter http://dnollk.se/, enligt:

* `http://dnollk.se/2015/?page=2` - Visar de 11-20 första nyheterna från 2015.

**Comment by Jassob** [comment]
@tairoman, vad tycker du?

On a side note, svenska eller engelska variabelnamn i querystringen?

* `http://dnollk.se/?sida=1?antal=20`
* `http://dnollk.se/?page=1?antal=20`

Hmm, svenska funkade ändå någorlunda vettigt...

**Comment by tairoman** [comment]
Paginering låter som en bra idé! Tycker att svenska är najs i url då resten av det är på svenska såvitt jag vet. Någon idé på implementation? Har aldrig gjort något sådant innan.

**Comment by Jassob** [comment]
Aah, jag har ju gjort sånt här på jobbet så jag kan kika på det!

**Comment by Jassob** [comment]
Det viktigaste är att vi löser slicing / hämtningen och droppandet av records i databasens queryset så vi inte hämtar alla records och sen dumpar 90% i efterhand...

**Comment by Jassob** [comment]
There is a branch for this issue, feature/pagination.
