### ISSUE TITLE
On mobile view you can scroll to the side when the content is pushed to the side

### ISSUE THREAD

**Issue by emilhem** [dtekcth/DNollK.se#17]
![screen shot 2016-07-25 at 13 27 55](https://cloud.githubusercontent.com/assets/1503789/17099946/c50f621e-526b-11e6-956d-9aa1a5792247.png)

**Comment by emilhem** [comment]
Should be solved with CSS and not JS as #18 does but still #18 solves the issue (after 700 ms).

**Comment by Jassob** [comment]
@emilhem, issue #13 is sort of related to making the transitions in CSS and not JS (as you've noted).

If I remember correctly the reason we use JS to make the transitions in the first place was that it was not completely trivial to get the CSS transition to trigger when changing the visibility of an element, or changing the max-width/height of an element..

If you have experience with CSS transitions you are more than welcome to give it a try!

// Jsb
