### ISSUE TITLE
Header image is wierd on larger monitors

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DNollK.se#23]
_From @emilhem on August 15, 2016 19:5_

Check it out!

![wops](https://cloud.githubusercontent.com/assets/1503789/17675870/fbf7baee-632b-11e6-9062-6a37c7a6eb7e.png)

_Copied from original issue: dtekcth/DNollK.se#25_

**Comment by Jassob** [comment]
It should be enough to set some kind of image width to 100%, I suppose it would stretch then?

**Comment by emilhem** [comment]
6e99fca5ba7aa11a9d8d5451dab64a1ac6d9cb76 fixes this issue.

**Comment by Jassob** [comment]
Nice! :D
