### ISSUE TITLE
Header image is wierd on larger monitors

### ISSUE THREAD

**Issue by emilhem** [dtekcth/DNollK.se#25]
Check it out!

![wops](https://cloud.githubusercontent.com/assets/1503789/17675870/fbf7baee-632b-11e6-9062-6a37c7a6eb7e.png)

**Comment by Jassob** [comment]
It should be enough to set some kind of image width to 100%, I suppose it would stretch then?

**Comment by Jassob** [comment]
This issue was moved to Jassob/DNollK.se#23
