### ISSUE TITLE
Nästa/Föregående Knapp

### ISSUE THREAD

**Issue by henkehagfeldt** [dtekcth/DNollK.se#33]
Byta plats på Nästa och Föregående knapp längst ner på Hemsidan för "Arr".

**Comment by Jassob** [comment]
Okej, så efter en massa onödiga missar (har ju inte datan på min dator så jag kan testa) så har jag nu bytt plats på nästa och föregående på både "Arr" och "Nyheter/Startsida".

Jag tror det makear mer sense även på nyheterna att det är såhär, men vi får väl se när ni lägger upp något :)
