### ISSUE TITLE
App-specifika inställningar i databas

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DNollK.se#6]
# Bakgrund 

Som det ser ut just nu är många inställningar hårdkodade i projektet, något som såklart inte är speciellt användarvänligt då det betyder att man måste in och rota i källkoden varje gång man vill ändra vissa saker. En lösning hade vart att föra in dessa inställningar i databasen istället och då låta admin-gränssnittet hantera det.

Saker som behöver finnas i en sådan tabell:

- [ ] Meta-Description (det som dyker som snippets i sökmotorer)
- [ ] Länkarna i "Bra länkar"
- [ ] Dokumenten i "Dokument"
- [ ] Inställningar för kalendern i "Schema" och sidebaren.
- [ ] Nollenkäten
- [ ] Kontakt information (utöver DNollK)
- [ ] Vilka uploads som ska vara header och logga
- Säkert mer...

**Comment by Jassob** [comment]
@tairoman, missade jag något bland sakerna som skulle in i databas?

**Comment by tairoman** [comment]
Kontaktinfo på "viktigt"-sidebaren och på kontakt-sidan(det som inte är dnollkmedlemmarna)

**Comment by Jassob** [comment]
Om vi löser denna; #11, så kan vi lägga till att kopplar header och logga till uploads, så får vi alt-texter på köpet.

**Comment by Jassob** [comment]
This issue was moved to Jassob/DNollK.se#17
