### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by Jassob** [dtekcth/DNollK.se#7]
# Bakgrund 
Det finns en del logik som avgör vilka kommittéer som hamnar på vilka sidor och så vidare som inte är dokumenterade.

Överhuvudtaget saknas överskådlig dokumentation över sidan vilket gör att överlämningen mellan år i stort sett är omöjlig och det är bara vi författare som vet vad som händer under huven.

Dokumentationen måste benämna:
- [ ] Vilka namn-konventioner har vi implementerat och hur påverkar det sidan.
- [ ] De olika modulerna i sidan;
  - [ ] Nyheter (startsidan)
  - [ ] Om
  - [ ] Kontakt
  - [ ] Arrangemang
  - [ ] Upload & admin-läget
  - [ ] Nollenkät
  - [ ] Schema
- [ ] Kort om hur man lägger till ändringar osv.
- Säkert mer...

**Comment by Jassob** [comment]
@tairoman, har jag glömt något i dokumentationen?

**Comment by tairoman** [comment]
Kommer inte på något mer atm!

**Comment by Jassob** [comment]
This issue was moved to Jassob/DNollK.se#18
